### PR TITLE
Fix wingpanel-indicator-network crashing

### PR DESCRIPTION
**Pull request by btd1337**
## Commit 1

If you do a clean installation of Pantheon, without using another DE as a base, for example Gnome, or XFCE, the `wingpanel` will crash.

The reason is that the `wingpanel-indicator-network` needs this `networkmanager` dependency, but it is not listed in the official repository.

Probably because it already comes with Ubuntu, but it does not come standard with Arch Linux.

screenshot from 2018-07-12 17-43-00

## Commit 2

elementary cmake repository was moved to junk repository into branch cmake

Currently this error occurs when u try install the package:

```
==> Starting build()...
CMake Error: The source directory "/home/arch/.cache/aurman/cmake-modules-elementary-git/src/cmake-modules-elementary" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
==> ERROR: A failure occurred in build().
Aborting...
2018-07-15 03:01:08,338 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-cf', '--noconfirm'] failed in directory /home/arch/.cache/aurman/cmake-modules-elementary-git
```

This second commit fix this issue

### CODE REVIEW

**Comment by alucryd** [comment]
I thought the word junk was explicit enough, elementary is ditching cmake altogether, those modules are irrelevant. They don't need fixing, they just need killing.

Also dependencies are sorted alphabetically, lines don't go over 80 characters, and there must be a new line between regular depends and sodepends.

**Comment by btd1337** [comment]
@alucryd Cmake Modules Elementary is still important for many applications that have not been rewritten.

For example, almost all applications created by https://github.com/artemanufrij still depend on it to run.

It would be worth keeping this dependency running until the main applications are rewritten.

**Comment by btd1337** [comment]
In this example, **HashIt** needs **cmake-modules-elementary** but this error occurs and update is crashed

screenshot from 2018-07-15 19-39-40

screenshot from 2018-07-15 19-39-55

**Comment by alucryd** [comment]
Those aren't official elementary apps, and honestly I couldn't care less about them, they should get up to speed with upstream. Plus I don't maintain those cmake modules in AUR anymore anyway.

**Comment by btd1337** [comment]
Right.

This error occurs because of this package that is outdated in the AUR and he search for cmake-modules-elementary dependency. Is it being held by you in the AUR?

-> https://aur.archlinux.org/packages/switchboard-plug-sharing-git/

fail

**Comment by btd1337** [comment]
I made all the changes you asked for.

Could you merge it?

**Comment by btd1337** [comment]
@alucryd  I made all the changes you asked for.

Could you merge it?

**Comment by btd1337** [comment]
@alucryd  I made all the changes you asked for.

Could you merge it?

**Pull request merged**
